export const CLUB_COLORS: Record<string, string> = {
    Liverpool: 'bg-red-600',
    Arsenal: 'bg-red-500',
    'Man City': 'bg-blue-500',
    Chelsea: 'bg-blue-700',
    Newcastle: 'bg-gray-800',
    Fulham: 'bg-black',
    'Aston Villa': 'bg-purple-700',
    Brighton: 'bg-cyan-500',
    Brentford: 'bg-red-600',
    Tottenham: 'bg-slate-500',
    'Crystal Palace': 'bg-red-700',
    Everton: 'bg-blue-800',
    'Man United': 'bg-red-700',
    'West Ham': 'bg-pink-700',
    Wolves: 'bg-yellow-500',
    'Leicester City': 'bg-blue-600',
    'Ipswich Town': 'bg-blue-600',
    Southampton: 'bg-red-700',
    'Nottm Forest': 'bg-red-600',
    Bournemouth: 'bg-red-700',
}